### ISSUE TITLE
"cannot find symbol"

### ISSUE THREAD

**Issue by Cygnus2112** [Appboy/appboy-react-sdk#159]
I've been getting this error when trying to build for android over the last few days:
``` 
> Task :app:compileReleaseDevelopmentJavaWithJavac FAILED
/home/runner/work/ ... /MainApplication.java:90: error: cannot find symbol
      Braze.getInstance(applicationContext).registerAppboyPushMessages(token);
                                           ^
  symbol:   method registerAppboyPushMessages(String)
  location: class Braze
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseDevelopmentJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
Any idea what's going on?

**Comment by Bucimis** [comment]
@Cygnus2112 the React SDK is still meant to work with Android v21.0.0. If you would like to use v22, you will need to update `registerAppboyPushMessages` to `setRegisteredPushToken`. (see https://github.com/Appboy/appboy-android-sdk/blob/1089c680a713b9e891ff5ef63946f3ba24cd2bef/CHANGELOG.md#breaking)

**Comment by Cygnus2112** [comment]
@Bucimis  Thanks! If I make the change to `setRegisteredPushToken` it builds successfully but crashes on startup. How do I pin the sdk version to Android v21.0.0?

**Comment by Bucimis** [comment]
@Cygnus2112 https://github.com/Appboy/appboy-react-sdk/blob/master/android/build.gradle#L25
