### ISSUE TITLE
Incompatible with RN 0.60+ / AndroidX

### ISSUE THREAD

**Issue by genuinezack** [Appboy/appboy-react-sdk#75]
After upgrading react-native to 0.60+ (in my case 0.61.2), which migrates to using AndroidX for Android support libraries, I'm getting the following errors on compile:

```
> Task :react-native-appboy-sdk:compileDebugJavaWithJavac FAILED
/my-app/node_modules/react-native-appboy-sdk/android/src/main/java/com/appboy/reactbridge/AppboyReactBridge.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/my-app/node_modules/react-native-appboy-sdk/android/src/main/java/com/appboy/reactbridge/AppboyReactBridge.java:590: error: cannot find symbol
  private @Nullable Card getCardById(String id) {
           ^
  symbol:   class Nullable
  location: class AppboyReactBridge
2 errors
```

It appears that the bridging code here needs to be updated to use the new `androidx.support` libraries to enable compilation going forward.

**Comment by genuinezack** [comment]
I think I was wrong - weirdly after updating a couple _unrelated_ SDKs and doing a full clean and rebuild, this error went away... Still don't have a great understanding of why, but I think this issue can be closed.
